version: "3"
services:
  vehicles-dbserver:
    image: mysql:latest
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSOWRD=root123
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - volume=./volume
    volumes:
      - /opt/mysql-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - application
networks:
  application: